corpus = "./data/english.json"
layouts = ["./core/test-layouts", "./layouts"] # can be an array of folders

[weights]
finger_usage = 35
sfbs = 35
sfs = 3
stretches = 19
sft = 5
inroll = 3
outroll = 3
alternate = 3
redirect = 35
onehandin = 2
onehandout = 0
full_scissors = 5
half_scissors = 1
full_scissors_skip = 2
half_scissors_skip = 1
magic_rule_penalty = 2
magic_repeat_penalty = 0

[weights.fingers]
lp = 77
lr = 32
lm = 24
li = 21
lt = 46
rt = 46
ri = 21
rm = 24
rr = 32
rp = 77
