corpus = "./data/english.json"
layouts = ["./core/test-layouts", "./layouts"] # can be an array of folders

[weights]
sfbs = 7
sfs = 2
stretches = 3
sft = 12
inroll = 7
outroll = 4
alternate = 4
redirect = 4
onehandin = 2
onehandout = 0
thumb = 0
full_scissors = 5
half_scissors = 1
full_scissors_skip = 2
half_scissors_skip = 1
magic_rule_penalty = 0
magic_repeat_penalty = 0

[weights.fingers]
lp = 77
lr = 32
lm = 24
li = 21
lt = 46
rt = 46
ri = 21
rm = 24
rr = 32
rp = 77
